services:
  risknotes:
    build: .
    container_name: risknotes_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/risknotes_dev
  
  postgres:
    image: postgres:18
    container_name: risknotes_postgres
    environment:
      POSTGRES_DB: risknotes_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - risknotes_pgdata:/var/lib/postgresql/data

volumes:
  risknotes_pgdata: